apiVersion: k3d.io/v1alpha2
kind: Simple
name: podtato-k3d
image: docker.io/rancher/k3s:v1.21.2-k3s1
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true